import { toTable } from "../lib/toon.js"

interface ChangelogEntry {
  version: string
  date: string
  description: string
}

const CHANGELOG: ChangelogEntry[] = [
  { version: "0.6.9", date: "2026-09-08", description: "Field-feedback round 6: the paid review loop at the phase gate. A pitboss ran six review rounds on one phase because every LOW fix re-verdicted a unit, which staled the review, which demanded a fresh seat; Codex replayed the ledger and found four enforcement holes, all closed here. REVIEW REQUIRED now states whether a stage:'verification' record would satisfy the gate right now (VERIFICATION ELIGIBLE with the exact record shape, baseline ts and direct-fix attempts filled in, or VERIFICATION NOT ELIGIBLE with the single blocker). Verification predicates: the baseline must be a complete seat (a failed, partial, or silent review cannot anchor one) and every attempt since the baseline must be a direct fix (a worker delegation or invoke_worker sidecar attempt in between is refused, not only the current attempt). Review retention keeps the 20-record cap but never evicts a record the gate is blocking on (a current confirmed finding, an unsuperseded failed or silent seat) or the baseline of a current verification record. A failed, partial, or silent seat is superseded for the INCOMPLETE REVIEW check by a later complete record from the same advisor at the same stage; confirmed findings on the superseded record still block. Implementor names the hint and the re-run rule at the checkpoint." },
  { version: "0.6.8", date: "2026-09-05", description: "Codex seat runs gpt-6-astra at xhigh reasoning (codex-cli 0.153.4 or newer; 0.152.0 reports the id needs a newer CLI, other *-astra spellings are refused on a ChatGPT account). invoke_advisor reads the model and reasoning effort Codex echoes in its header, reports model_served and reasoning_effort, and treats a substituted model as a failed seat, matching the Gemini rule." },
  { version: "0.6.7", date: "2026-09-04", description: "Gemini seat pinned to gemini-3.1-pro-preview with served-model checking. 0.6.6's gemini-3.8-flash pin was accepted by the CLI but served by gemini-3.5-flash on the tested account, silently (exit 0, plausible answer); 3.7-flash the same. invoke_advisor and capability_check run gemini with --output-format json, report model_requested/model_served and thinking tokens from the run stats, and treat a served model other than the pinned one as a failed seat (model_substituted). Older CLIs printing text: model_served unknown, handled as before." },
  { version: "0.6.6", date: "2026-09-04", description: "Gemini advisor seat runs gemini-3.8-flash: invoke_advisor and capability_check pass the model id directly instead of the arch-review alias, which existed only in one machine's ~/.gemini/settings.json. Verified through the CLI (an unknown id fails with ModelNotFoundError, so the answer is not a fallback). Gitleaks allowlist restores the two aider fixture tokens that remain in history after the 0.6.3 file removal." },
  { version: "0.6.5", date: "2026-09-04", description: "Field-feedback round 5. invoke_advisor reports exit 0 with empty or echoed stdout as completion: failed with the stderr tail (no in-tool retry). session_orient state_drift fires only on a progress entry marked complete for a unit the ledger has not passed (or progress units with no ledger phases); stale/ahead/orphan entries are a non-blocking progress_advisories field, and pointer-order disagreement never blocks. authorize_attempts records one owner grant of 1-10 attempts past the cap, charged per attempt (cap_grants[], attempt_grants in orient, cap_grant in the unit view); refused below the cap, while a grant is open, or together with user_override (AMBIGUOUS OVERRIDE); a pass closes it. Review currency needs an independent review or an eligible stage:'verification' record — cross_exam never counts; council payloads carry stage: independent. stage:'verification' with evidence {baseline_review_ts, units[{unit_id, attempt}], files, tests, probe} stands in for a seat only for linked direct-fix re-verdicts on an unscoped phase with no confirmed finding above LOW since the baseline. checked[] entries up to 400 chars. complete_unit counts legacy checkbox lines outside the fence (legacy_checkbox_candidates) and never edits them." },
  { version: "0.6.4", date: "2026-09-04", description: "Field-feedback round 4. The delegation cap guards the pass, not only the delegation record: a pass needs an attempt recorded after the latest rejection or fail verdict (ATTEMPT REQUIRED) and, past the cap, user_override (recorded as cap_override); the cap counts failed attempts since the unit last passed; fail verdicts count; a Direct Fix is recorded as an attempt via set_unit_status { s:'ip', direct_fix }; counts live in server-written per-unit scalars (attempt_seq, epoch_failed, last_failed_attempt, needs_attempt) so the 20-entry array caps cannot lose them; the post-21st-delegation rejection stamp is fixed; session_orient reports attempt_blocks. record_review requires a classification on every finding (earlier unclassified reviews read as INCOMPLETE REVIEW). bundle_status compares dist/, package.json, and the stack profile override against a process-start snapshot and answers restart_recommended true/false/n/a with the reason. Journal msg (400) and review checked (50 x 200) limits named in the tool descriptions. Advisor Grounding Protocol: bounded-verification wording, refusal recorded as completion:'failed' and retried once. One-call review recording declined." },
  { version: "0.6.3", date: "2026-09-04", description: "Surface reduction. aider_worker removed (tool, worktree library, Python harness, tests); failure taxonomy 21 -> 17 active stages with a read-only legacy set so old sidecars keep their refunded classification; .foremanenv drops aider-cli and the NUM_CTX/MAX_REFLECTIONS/REASONING_TAG keys. Tarball ships only runtime files via a package.json files whitelist (dist/, src/skills/, HOST-CONTRACT.md, README, LICENSE, bundled deps); build cleans dist/ first; no declarations or source maps; a test pins the packed manifest. Publish smoke also activates a protocol, serves ethos, checks the installed file set, and runs --diag from the installed package. Journal codes trimmed to 15 (twelve never-emitted codes plus CAP_WAIVER removed; old journals still parse). Loopback regression test for a configured invoke_council seat. Default tool count 26 (27 under Codex)." },
  { version: "0.6.2", date: "2026-09-04", description: "Docs rewrite + field-feedback round 3. README and the 16-page docs site rewritten plain (actor named, enforced vs instructed separated, copy-paste prompts). Phase gate: only reviews recorded at/after the latest unit verdict count; refuses on a 'confirmed' finding (CONFIRMED FINDINGS) or an incomplete review — partial/failed, or zero findings with no checked[] (INCOMPLETE REVIEW); overrides recorded on the phase. Per-operation data shapes moved into the write tools' input schema (hosts clip descriptions at ~2,000 chars); every description held under the clip by a test. normalize_review parses bounded item blocks (bold-numbered items, Severity: mid-line or next line, — HIGH: after a location, [P0]–[P3], tables, consecutive headings). bundle_status reports running vs on-disk version and restart_recommended. Line-endings clause in the fan-out rule and host contract; aider_worker worktrees use core.autocrlf=false. run_tests: gofmt and golangci-lint allowlisted with fail_on_stdout. Journal msg limit 400. Implementor spec-amendment rule for SPEC_GAP." },
  { version: "0.6.1", date: "2026-09-03", description: "Field-feedback round 2. Schema errors from write_ledger/write_journal/write_progress are one hint per field plus the operation's expected data shape (no more raw Zod dumps). The Step 4.5 preflight is attested on the delegated write: s:'delegated' requires data.preflight { symbols_grepped, self_consistent: true, telemetry? } and stores it on the delegation entry. Journal codes SPEC_GAP (gap decided, recorded, continuing) and GATE_OVERRIDE (user forced past a checkpoint, same session kept). invoke_advisor drops stderr on success unless stdout itself was truncated (then a 40-line tail). run_tests gains opt-in strip_patterns and tail_lines output shaping." },
  { version: "0.6.0", date: "2026-09-03", description: "Field-feedback release (8 items + 3 Codex-found root causes). normalize_review parses real advisor layouts (numbered/bulleted markers in any decoration, Severity: fields, Finding N headings, trailing tokens) and never turns unmarked prose into a finding (new unparsed_lines, findings_json line, pipe-safe table). write_journal/write_ledger descriptions carry exact per-operation data shapes generated from the validation schemas and pinned by a contract test. Ledger: add_rejection on a passed unit reopens it to pending; the phase gate refuses g:'pass' with zero record_review entries (user_override recorded as review_override); set_verdict stamps first_pass_ts once; record_review gains completion/checked/limitations/stage. session_orient orders phase and unit ids naturally (p2 before p10) and reports last_completed_unit as the first-pass frontier plus additive latest_pass_verdict_unit/ts. Implementor: Direct Fix eligibility rule (literal substitutions on host-native-delegated units only), brief self-consistency + telemetry reserved-name preflight steps, checkpoint examined-list contract with partial/cross_exam staging. Spec generator: fenced machine-owned Ledger Status block + fence-free Unit Plan (no duplicate PROGRESS checklists), G10, state_tracking_policy check-ignore step (never writes .gitignore)." },
  { version: "0.5.14", date: "2026-08-08", description: "Field-feedback release — declare_phase_units makes the spec's expected unit set a ledger fact: phase gates block g:'pass' while any declared id is unregistered, session_orient resumes at the first declared-but-unseeded unit (new missing_declared_units field) instead of misreporting retry_phase_gate, declared sets are frozen behind passed gates and join the D2b gate-staleness hash, and an auditable retire path (mandatory reason, declared_log tombstones) corrects typos without manual ledger edits. The progress checklist renders declared-but-unregistered units instead of erasing them. session_orient drift detection is now bidirectional (progress marking the ledger's resume unit complete is flagged; partial progress files stay non-drift). read_ledger paged queries emit query-specific truncation recovery hints. Implementor sessions probe advisors once at init_session and record version/auth_status; checkpoints reuse the probe. The claude-code fan-out rule gained a concrete worktree parallel-edit procedure. Diagram preview: cursor-centered wheel zoom, drag pan, toolbar + keyboard shortcuts, and client-side PNG/SVG/.mmd export under the existing strict CSP." },
  { version: "0.5.13", date: "2026-08-05", description: "Production-migration hardening: shared-tree editing workers receive an explicit Git-mutation denylist, run sequentially unless isolated, and require a before/after repository-state guard with no automatic recovery; mature ledger reads are filtered, paged, cell-bounded, and refuse oversized full output; session_orient is the ledger-authoritative resume path with gate retries, timestamp-based completion order, and progress drift reporting; run_tests supports shell-free Gradle wrappers including Windows GradleWrapperMain; journal phases accept canonical string ids; repeated green-but-unobservable checkpoint blocks escalate to mutation evidence and then owner arbitration." },
  { version: "0.5.12", date: "2026-08-03", description: "Adaptive Review Council — new EXPERIMENTAL invoke_council tool runs N remote read-only seats across M risk lenses over one evidence packet in parallel, returning ledger-shaped findings for the host to moderate and the user to arbitrate. Entirely optional: with no seats configured it returns status: unavailable, names the next rung of the deliberation ladder, and Foreman behaves exactly as before. Versioned 7-lens catalog (contract, architecture, state, security, data, tests, operability); each seat sees the packet plus ONE lens card. Seats configurable from .foremanenv or the new ~/.foreman-mcp/.env operator store, home-store-wins per seat so a model swaps without editing the repo; each seat reports its source. [CWE-522] the API key resolves from the same store that supplied the endpoint, so a repo file pointing at a local box and a home store on a hosted provider cannot misdeliver a credential. [CWE-532] every qualifying home-store value is registered for redaction, closing a gap where a second credential was invisible to scrub() and the outbound secret gate. Chat transport extracted to lib/chatTransport.ts and shared byte-for-byte with invoke_worker (two-phase timeouts, byte-capped stream, closed status mapping); invoke_worker behavior unchanged. Deliberation ladder is now 5 recorded rungs; unavailable and fail both drop a rung and are never a passed review. Optional zero-dependency Langfuse tracing, off by default." },
  { version: "0.5.11", date: "2026-07-28", description: "MCP TypeScript SDK v2 migration — split server/client packages, Zod 4 Standard Schema validation, strict input contracts, top-level tool titles, validated scalar output schemas with structuredContent, modern plus legacy stdio negotiation, split-package diagnostics, wire-level protocol regression coverage, and bundled offline-installable runtime dependencies. Package inspection excludes the workspace-local .tmp npm cache. README and HOST-CONTRACT distinguish aider_worker's MCP-managed worktree from host-enforced native-worker isolation without claiming git-stash or arbitrary user-edit recovery." },
  { version: "0.5.10", date: "2026-07-13", description: "Advisor latency update — Codex reviews run gpt-5.6-sol at xhigh reasoning effort; invoke_advisor timeout budget raised (default 15 min, cap 30 min) so Sol-class thinking time is not killed mid-reasoning and misrecorded as advisor-unavailable. CI hygiene: gitleaks fixture allowlist entries + dojo snapshot path allowlist; the python-missing capability-probe test skips on hosts where python cannot be hidden from PATH." },
  { version: "0.5.7", date: "2026-07-10", description: "Native Codex host profile: Codex spawn_agent workers (gpt-5.6-luna preferred only when host-confirmed), headless Claude Fable 5 max + Gemini independent advisors, host-rendered provider-neutral review protocol, and an authoritative runtime preamble for stale skill overrides. Claude CLI versions are telemetry only. Crucible remains an optional future custom/local-model worker runner and does not own native-host pitboss context." },
  { version: "0.5.6", date: "2026-07-09", description: "Review-model update - Codex reviews now run gpt-5.6-sol at ultra reasoning effort; Cursor Advisor A uses the matching gpt-5.6-sol-ultra model slug. Added direct regression coverage for the Codex invocation arguments." },
  { version: "0.4.0", date: "2026-07-01", description: "Cost-tier telemetry + durable review records — Fusion-inspired ledger auditability. set_unit_status now accepts optional tier ('cheap'|'standard'|'premium') + route_reason, recorded on the delegated transition and appended to a new per-unit append-only delegations[] history (survives the brief overwrite on fix re-delegation; attempt numbers stay monotonic across a 20-entry cap). A new record_review write op persists advisor findings (severity/file/line/description/classification) to Phase.reviews[] at checkpoints; read_ledger gains a 'reviews' query and the verdicts view adds a tier column. ReviewFinding is consolidated into types.ts (shared with normalize_review). The implementor protocol records tier on delegation and adds a guarded tier-escalation rule — a fix worker escalates to a higher tier only when route_reason cites a refined brief or an advisor diagnosis, never a blind bump. applyOperation gained an exhaustiveness guard so an unhandled operation throws instead of silently no-opping. All new fields are additive/optional — backward-compatible with pre-0.4.0 ledgers; no ledger schema-version bump." },
  { version: "0.3.0", date: "2026-06-13", description: "preview_diagram (23rd tool) — live, in-project Mermaid workshop. Writes Docs/diagrams/<id>.mmd (the versioned source of truth) and serves an auto-refreshing browser preview over SSE; mermaid renders client-side from a vendored bundle (no Chromium), fully offline. This is Foreman's first network listener — loopback-only (127.0.0.1), per-session token-gated, and Host/Origin-validated against DNS rebinding (no CORS headers). design-partner, spec-man, and lighttask opt in to show data flows / architecture live instead of dumping ASCII or raw Mermaid text. architecture-beta and mindmap diagram types are unsupported under the strict no-unsafe-eval render policy." },
  { version: "0.2.2", date: "2026-06-13", description: "Advisor compression fix. Successful invoke_advisor output (prose) is no longer lossy-compressed — it passed through the log compressor when a review quoted >=3 error lines, silently dropping the recommendations. Successful advisor output now passes through; only FAILED advisor diagnostics are compressed (recoverable via retrieve_original). The redundant advisor STDERR (CLI banner + echoed prompt + a duplicate of STDOUT + token count) is trimmed on clean success, with the token count preserved as a tokens_used meta line. Fixed a meta-head duplication in compressed run_tests output. retrieve_original and invoke_advisor descriptions now cue agents to retrieve the original when a compressed summary is insufficient." },
  { version: "0.2.1", date: "2026-06-12", description: "Compression pilot fix #1 — compressed run_tests/invoke_advisor output now retains the tool's leading meta block (exit_code, passed, timed_out, truncated / cli) by re-prepending it onto the compressed digest. Previously the log compressor's error-extraction dropped these lines, costing agents at-a-glance pass/fail status. Never applied to smart_crusher (JSON) output; skipped when the digest already contains the block." },
  { version: "0.2.0", date: "2026-06-12", description: "Compression pilot — context-crush integration. run_tests and invoke_advisor outputs >=2048 bytes that detect as log/diff/json are compressed with reversible CCR storage; compressed output carries a <<ccr:HASH>> marker and the new retrieve_original tool (22nd tool) exchanges the hash for the exact original. DEFAULT ON for the pilot; kill switch FOREMAN_COMPRESSION=0; per-tool allowlist FOREMAN_COMPRESSION_TOOLS (default run_tests,invoke_advisor); TTL via CONTEXT_CRUSH_CCR_TTL_SECONDS (default 300s). Prose/text outputs pass through unchanged (detect_passthrough); originals are always stored before lossy output escapes (fail-open). context-crush ships as a bundled dependency so the packed tarball is self-contained." },
  { version: "0.1.3", date: "2026-06-09", description: "Ledger invariant enforcement — protocol prose and mechanical enforcement re-synced. The delegated step (ip -> delegated -> pass) is now documented in the implementor protocol and write_ledger tool description (previously every first pass verdict hit VERDICT BLOCKED and the model learned the sequence from the error). update_phase_gate g:'pass' is blocked unless every unit in the phase has a pass verdict; empty phases cannot pass a gate. Pass verdicts on phases scoped has_tests:false or has_build:false mechanically require an attestation note. set_phase_scope's test-file mismatch warning now surfaces in the tool result, not just stderr. Read paths (read_ledger, session_orient, write_progress) report ledger_corrupt instead of silently treating a corrupt ledger as a fresh project, and never rename the corrupt file; writes warn with the .corrupt backup path. read_ledger single-unit and verdicts views now include via and note." },
  { version: "0.1.2", date: "2026-06-08", description: "Citation verification and codex CLI lookup fix. Adds verify_citations - a deterministic tool that re-reads [OBSERVED]/[IMPLEMENTED] file:line evidence and reports CONFIRMED/DRIFTED/MISSING/UNANCHORED - plus a shared citation-verification protocol gate in spec-man and doc-man (completion requires every claim-bearing ref CONFIRMED or explicitly downgraded). Fixes capability_check reporting an authenticated codex as auth_status: expired (codex health now uses 'codex login status' instead of a full codex exec with a stale model under a 15s timeout). Codex advisor now runs gpt-5.5 at high reasoning effort; Cursor advisor slug is gpt-5.5-high. Backward compatible: existing unanchored citations remain valid." },
  { version: "0.1.1", date: "2026-06-08", description: "Tool metadata release - activation descriptions now telegraph spec-man stale-plan re-evaluation, Atlas/Graphify code-surfacing, Plan Delta Ladder promotion boundaries, lighttask escalation, and optional LangGraph-style runtime-control triggers for branching multi-session workflows." },
  { version: "0.1.0", date: "2026-06-06", description: "First minor release for the lighttask/spec/doc protocol family - promotes surgical-task, spec-man, and doc-man tool heads; adds optional Graphify-backed project atlas guidance for spec-man grounding and lighttask re-evaluation on stale resume context." },
  { version: "0.0.10", date: "2026-06-06", description: "Lighttask/spec/doc protocol release - adds lighttask, spec_man, and doc_man skill activation tools; introduces surgical-task gates for workspace classification, git context, spec freshness, grounding, bypass waivers, and adversarial review; adds grounded spec/documentation protocols and deterministic capability-check tests." },
  { version: "0.0.9", date: "2026-05-06", description: "CI hygiene + semver fix — release workflow packs into release-pkg/ (gitignored) instead of the committed artifacts/ archive, so the GitHub Release attachment ships only the current version's tarball. README install URL switched to the Release download URL. Version bump skips 0.0.8.1 (npm rejects 4-segment versions). No runtime changes." },
  { version: "0.0.8", date: "2026-05-06", description: "Cursor host mode — host-aware skill rendering via placeholders (worker_invoke, advisor_a, advisor_b); --host CLI flag and FOREMAN_HOST env var (claude-code default, cursor, codex); host_status tool; capability_check returns synthetic available in cursor mode (Task subagents). Default behavior unchanged for Claude Code / Codex CLI users." },
  { version: "0.0.7.5", date: "2026-04-17", description: "Workflow hygiene patch: ledger honesty (via field, phase scope), session_orient tool, PROGRESS.md fenced auto-sync, skill trim ~30% via common protocol extraction" },
  { version: "0.0.7", date: "2026-04-11", description: "Pentest triage fixes — remove npx from run_tests allowlist + deny via env (INJ-008), regex filter on FOREMAN_TEST_ALLOWLIST (INJ-007), settled guard on runTests data handlers (EXH-004), ComSpec via SystemRoot (INJ-006), block format for invoke_advisor output (INJ-009)" },
  { version: "0.0.6", date: "2026-04-11", description: "Security hardening, cross-platform CLI invoker, session journal — input length caps on all inline schemas, normalize_review schema extraction, error_log FIFO cap, cross-platform invoke_advisor tool (SpawnPlan + stdin delivery + .cmd shim wrapping + CRLF handling), capabilityCheck adopts SpawnPlan, runTests rejects .cmd runners on Windows, session journal for operational telemetry" },
  { version: "0.0.5", date: "2026-04-09", description: "run_tests tool — bounded test output with command allowlist; externalCli buffer cap; security hardening: input length caps, rejection array cap, absolute CLI path resolution, generic skill loader errors (pentest triage v0.0.5)" },
  { version: "0.0.4", date: "2026-04-08", description: "Skill activation tools — design_partner, spec_generator, pitboss_implementor pipe skill protocols into LLM context as tools; skill:// resources kept for backward compatibility" },
  { version: "0.0.3-3", date: "2026-04-07", description: "Pitboss enforcement gate — set_verdict(pass) blocked without prior delegation; delegation requires worker brief (min 20 chars)" },
  { version: "0.0.3-2", date: "2026-04-07", description: "session_hint enforces pitboss/worker pattern — workflow directive tells remote sessions to read implementor skill and deliberate with Codex CLI" },
  { version: "0.0.3-1", date: "2026-04-06", description: "session_hint in read_progress output — actionable directive for LLM session start" },
  { version: "0.0.3", date: "2026-04-05", description: "Tool schema enums for write_ledger/write_progress operations, design-partner YIELD directives for interactive pause" },
  { version: "0.0.2.1", date: "2026-04-04", description: "DX fix — document valid operations in write_ledger/write_progress tool descriptions, fix server version mismatch" },
  { version: "0.0.2", date: "2026-04-04", description: "MCP skill delivery — design-partner, spec-generator, implementor as MCP resources; AB test validated against native skills" },
  { version: "0.0.1", date: "2026-04-02", description: "Initial architecture remediation — ledger, progress, external CLI" },
]

export function changelog(sinceVersion?: string): string {
  let entries = CHANGELOG
  if (sinceVersion) {
    const idx = CHANGELOG.findIndex(e => e.version === sinceVersion)
    entries = idx >= 0 ? CHANGELOG.slice(0, idx) : CHANGELOG
  }
  return toTable(["version", "date", "description"], entries.map(e => [e.version, e.date, e.description]))
}
