import { toTable } from "../lib/toon.js"

interface ChangelogEntry {
  version: string
  date: string
  description: string
}

const CHANGELOG: ChangelogEntry[] = [
  { version: "0.4.0", date: "2026-07-01", description: "Cost-tier telemetry + durable review records — Fusion-inspired ledger auditability. set_unit_status now accepts optional tier ('cheap'|'standard'|'premium') + route_reason, recorded on the delegated transition and appended to a new per-unit append-only delegations[] history (survives the brief overwrite on fix re-delegation; attempt numbers stay monotonic across a 20-entry cap). A new record_review write op persists advisor findings (severity/file/line/description/classification) to Phase.reviews[] at checkpoints; read_ledger gains a 'reviews' query and the verdicts view adds a tier column. ReviewFinding is consolidated into types.ts (shared with normalize_review). The implementor protocol records tier on delegation and adds a guarded tier-escalation rule — a fix worker escalates to a higher tier only when route_reason cites a refined brief or an advisor diagnosis, never a blind bump. applyOperation gained an exhaustiveness guard so an unhandled operation throws instead of silently no-opping. All new fields are additive/optional — backward-compatible with pre-0.4.0 ledgers; no ledger schema-version bump." },
  { version: "0.3.0", date: "2026-06-13", description: "preview_diagram (23rd tool) — live, in-project Mermaid workshop. Writes Docs/diagrams/<id>.mmd (the versioned source of truth) and serves an auto-refreshing browser preview over SSE; mermaid renders client-side from a vendored bundle (no Chromium), fully offline. This is Foreman's first network listener — loopback-only (127.0.0.1), per-session token-gated, and Host/Origin-validated against DNS rebinding (no CORS headers). design-partner, spec-man, and lighttask opt in to show data flows / architecture live instead of dumping ASCII or raw Mermaid text. architecture-beta and mindmap diagram types are unsupported under the strict no-unsafe-eval render policy." },
  { version: "0.2.2", date: "2026-06-13", description: "Advisor compression fix. Successful invoke_advisor output (prose) is no longer lossy-compressed — it passed through the log compressor when a review quoted >=3 error lines, silently dropping the recommendations. Successful advisor output now passes through; only FAILED advisor diagnostics are compressed (recoverable via retrieve_original). The redundant advisor STDERR (CLI banner + echoed prompt + a duplicate of STDOUT + token count) is trimmed on clean success, with the token count preserved as a tokens_used meta line. Fixed a meta-head duplication in compressed run_tests output. retrieve_original and invoke_advisor descriptions now cue agents to retrieve the original when a compressed summary is insufficient." },
  { version: "0.2.1", date: "2026-06-12", description: "Compression pilot fix #1 — compressed run_tests/invoke_advisor output now retains the tool's leading meta block (exit_code, passed, timed_out, truncated / cli) by re-prepending it onto the compressed digest. Previously the log compressor's error-extraction dropped these lines, costing agents at-a-glance pass/fail status. Never applied to smart_crusher (JSON) output; skipped when the digest already contains the block." },
  { version: "0.2.0", date: "2026-06-12", description: "Compression pilot — context-crush integration. run_tests and invoke_advisor outputs >=2048 bytes that detect as log/diff/json are compressed with reversible CCR storage; compressed output carries a <<ccr:HASH>> marker and the new retrieve_original tool (22nd tool) exchanges the hash for the exact original. DEFAULT ON for the pilot; kill switch FOREMAN_COMPRESSION=0; per-tool allowlist FOREMAN_COMPRESSION_TOOLS (default run_tests,invoke_advisor); TTL via CONTEXT_CRUSH_CCR_TTL_SECONDS (default 300s). Prose/text outputs pass through unchanged (detect_passthrough); originals are always stored before lossy output escapes (fail-open). context-crush ships as a bundled dependency so the packed tarball is self-contained." },
  { version: "0.1.3", date: "2026-06-09", description: "Ledger invariant enforcement — protocol prose and mechanical enforcement re-synced. The delegated step (ip -> delegated -> pass) is now documented in the implementor protocol and write_ledger tool description (previously every first pass verdict hit VERDICT BLOCKED and the model learned the sequence from the error). update_phase_gate g:'pass' is blocked unless every unit in the phase has a pass verdict; empty phases cannot pass a gate. Pass verdicts on phases scoped has_tests:false or has_build:false mechanically require an attestation note. set_phase_scope's test-file mismatch warning now surfaces in the tool result, not just stderr. Read paths (read_ledger, session_orient, write_progress) report ledger_corrupt instead of silently treating a corrupt ledger as a fresh project, and never rename the corrupt file; writes warn with the .corrupt backup path. read_ledger single-unit and verdicts views now include via and note." },
  { version: "0.1.2", date: "2026-06-08", description: "Citation verification and codex CLI lookup fix. Adds verify_citations - a deterministic tool that re-reads [OBSERVED]/[IMPLEMENTED] file:line evidence and reports CONFIRMED/DRIFTED/MISSING/UNANCHORED - plus a shared citation-verification protocol gate in spec-man and doc-man (completion requires every claim-bearing ref CONFIRMED or explicitly downgraded). Fixes capability_check reporting an authenticated codex as auth_status: expired (codex health now uses 'codex login status' instead of a full codex exec with a stale model under a 15s timeout). Codex advisor now runs gpt-5.5 at high reasoning effort; Cursor advisor slug is gpt-5.5-high. Backward compatible: existing unanchored citations remain valid." },
  { version: "0.1.1", date: "2026-06-08", description: "Tool metadata release - activation descriptions now telegraph spec-man stale-plan re-evaluation, Atlas/Graphify code-surfacing, Plan Delta Ladder promotion boundaries, lighttask escalation, and optional LangGraph-style runtime-control triggers for branching multi-session workflows." },
  { version: "0.1.0", date: "2026-06-06", description: "First minor release for the lighttask/spec/doc protocol family - promotes surgical-task, spec-man, and doc-man tool heads; adds optional Graphify-backed project atlas guidance for spec-man grounding and lighttask re-evaluation on stale resume context." },
  { version: "0.0.10", date: "2026-06-06", description: "Lighttask/spec/doc protocol release - adds lighttask, spec_man, and doc_man skill activation tools; introduces surgical-task gates for workspace classification, git context, spec freshness, grounding, bypass waivers, and adversarial review; adds grounded spec/documentation protocols and deterministic capability-check tests." },
  { version: "0.0.9", date: "2026-05-06", description: "CI hygiene + semver fix — release workflow packs into release-pkg/ (gitignored) instead of the committed artifacts/ archive, so the GitHub Release attachment ships only the current version's tarball. README install URL switched to the Release download URL. Version bump skips 0.0.8.1 (npm rejects 4-segment versions). No runtime changes." },
  { version: "0.0.8", date: "2026-05-06", description: "Cursor host mode — host-aware skill rendering via placeholders (worker_invoke, advisor_a, advisor_b); --host CLI flag and FOREMAN_HOST env var (claude-code default, cursor, codex); host_status tool; capability_check returns synthetic available in cursor mode (Task subagents). Default behavior unchanged for Claude Code / Codex CLI users." },
  { version: "0.0.7.5", date: "2026-04-17", description: "Workflow hygiene patch: ledger honesty (via field, phase scope), session_orient tool, PROGRESS.md fenced auto-sync, skill trim ~30% via common protocol extraction" },
  { version: "0.0.7", date: "2026-04-11", description: "Pentest triage fixes — remove npx from run_tests allowlist + deny via env (INJ-008), regex filter on FOREMAN_TEST_ALLOWLIST (INJ-007), settled guard on runTests data handlers (EXH-004), ComSpec via SystemRoot (INJ-006), block format for invoke_advisor output (INJ-009)" },
  { version: "0.0.6", date: "2026-04-11", description: "Security hardening, cross-platform CLI invoker, session journal — input length caps on all inline schemas, normalize_review schema extraction, error_log FIFO cap, cross-platform invoke_advisor tool (SpawnPlan + stdin delivery + .cmd shim wrapping + CRLF handling), capabilityCheck adopts SpawnPlan, runTests rejects .cmd runners on Windows, session journal for operational telemetry" },
  { version: "0.0.5", date: "2026-04-09", description: "run_tests tool — bounded test output with command allowlist; externalCli buffer cap; security hardening: input length caps, rejection array cap, absolute CLI path resolution, generic skill loader errors (pentest triage v0.0.5)" },
  { version: "0.0.4", date: "2026-04-08", description: "Skill activation tools — design_partner, spec_generator, pitboss_implementor pipe skill protocols into LLM context as tools; skill:// resources kept for backward compatibility" },
  { version: "0.0.3-3", date: "2026-04-07", description: "Pitboss enforcement gate — set_verdict(pass) blocked without prior delegation; delegation requires worker brief (min 20 chars)" },
  { version: "0.0.3-2", date: "2026-04-07", description: "session_hint enforces pitboss/worker pattern — workflow directive tells remote sessions to read implementor skill and deliberate with Codex CLI" },
  { version: "0.0.3-1", date: "2026-04-06", description: "session_hint in read_progress output — actionable directive for LLM session start" },
  { version: "0.0.3", date: "2026-04-05", description: "Tool schema enums for write_ledger/write_progress operations, design-partner YIELD directives for interactive pause" },
  { version: "0.0.2.1", date: "2026-04-04", description: "DX fix — document valid operations in write_ledger/write_progress tool descriptions, fix server version mismatch" },
  { version: "0.0.2", date: "2026-04-04", description: "MCP skill delivery — design-partner, spec-generator, implementor as MCP resources; AB test validated against native skills" },
  { version: "0.0.1", date: "2026-04-02", description: "Initial architecture remediation — ledger, progress, external CLI" },
]

export function changelog(sinceVersion?: string): string {
  let entries = CHANGELOG
  if (sinceVersion) {
    const idx = CHANGELOG.findIndex(e => e.version === sinceVersion)
    entries = idx >= 0 ? CHANGELOG.slice(0, idx) : CHANGELOG
  }
  return toTable(["version", "date", "description"], entries.map(e => [e.version, e.date, e.description]))
}
